name: tt2022ssd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.6.4
  - pip
  - numpy>=1.15.0
  - scipy>=1.4.0
  - cudatoolkit=10.2
  - pylops
  - segyio
  - scikit-learn
  - pandas
  - matplotlib
  - ipython
  - jupyter
  - pytorch
  - tqdm
  - pip:
    - image
    - torchsummary
    - torchviz